POST /submit_idea HTTP/1.1
Host: 127.0.0.1:5000
Content-Type: application/json; charset=utf-8

{
    "title": "HELLO",
    "category": "yo",
    "description": "yo"
}

###

GET /home HTTP/1.1
Host: 127.0.0.1:5000
Content-Type: application/json; charset=utf-8
